stages:
  - generate-site
  - build-dev

generate-site:
  script:
    - 'mvn site'
  only:
    branches:
      - dev
  when: manual
  tags:
    - shell

build-dev:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    branches:
      - dev
  when: manual
  tags:
    - shell
