# version: 2.1
# workflows:
#   maven_test:
#     jobs:
#       build:
#         docker:
#           - image: circleci/jdk8:0.1.1
#             - command: 'mvn test'    

orbs:
  maven: circleci/maven@x.y
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'
