# version: 2.1
# workflows:
#   maven_test:
#     jobs:
#       build:
#         docker:
#           - image: circleci/jdk8:0.1.1
#             - command: 'mvn test'    

version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - run: mvn test

