  
orbs:
  maven: circleci/maven@1.0.0
  docker: circleci/docker@1.0.0

version: 2.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 'site'
      - check-and-build-only:
          executor: docker/machine
          steps:
            - checkout
            - docker/check
            - docker/build:
                image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

