# version: 2.1
# workflows:
#   maven_test:
#     jobs:
#       build:
#         docker:
#           - image: circleci/jdk8:0.1.1
#             - command: 'mvn test'    

orbs:
  maven: circleci/maven@1.0.0
version: 2.1

parameters:
  maven_command:
    default: mvn
workflows:
  maven_build:
    jobs:
      - run:
          command: << parameters.maven_command >> site
